return  {
    -- Movement
    A = 34, -- INPUT_MOVE_LEFT_ONLY
    B = 29, -- INPUT_SPECIAL_ABILITY_SECONDARY
    C = 26, -- INPUT_LOOK_BEHIND
    D = 35, -- INPUT_MOVE_RIGHT_ONLY
    E = 38, -- INPUT_PICKUP
    F = 23, -- INPUT_ENTER
    G = 47, -- INPUT_DETONATE
    H = 74, -- INPUT_VEH_HEADLIGHT
    I = 157, -- INPUT_SELECT_WEAPON_UNARMED
    J = 182, -- INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY
    K = 311, -- INPUT_REPLAY_SHOWHOTKEY
    L = 7,   -- INPUT_CINEMATIC_SLOWMO
    M = 244, -- INPUT_INTERACTION_MENU
    N = 249, -- INPUT_PUSH_TO_TALK
    O = 243, -- INPUT_ENTER_CHEAT_CODE
    P = 199, -- INPUT_FRONTEND_PAUSE
    Q = 44,  -- INPUT_COVER
    R = 45,  -- INPUT_RELOAD
    S = 33,  -- INPUT_MOVE_DOWN_ONLY
    T = 245, -- INPUT_MP_TEXT_CHAT_ALL
    U = 303, -- INPUT_REPLAY_SCREENSHOT
    V = 0,   -- INPUT_NEXT_CAMERA
    W = 32,  -- INPUT_MOVE_UP_ONLY
    X = 73,  -- INPUT_VEH_DUCK
    Y = 246, -- INPUT_MP_TEXT_CHAT_TEAM
    Z = 20,  -- INPUT_MULTIPLAYER_INFO

    -- Camera
    RButton = 25, -- INPUT_AIM
    MouseWheelUp = 15, -- INPUT_WEAPON_WHEEL_PREV
    MouseWheelDown = 14, -- INPUT_WEAPON_WHEEL_NEXT
    V = 0, -- INPUT_NEXT_CAMERA

    -- Combat
    LButton = 24, -- INPUT_ATTACK
    Tab = 37, -- INPUT_SELECT_WEAPON

    -- Vehicle
    G = 47, -- INPUT_DETONATE

    -- Miscellaneous
    Esc = 200, -- INPUT_FRONTEND_PAUSE
    Tilde = 243, -- INPUT_ENTER_CHEAT_CODE
    M = 244, -- INPUT_INTERACTION_MENU
    P = 199, -- INPUT_FRONTEND_PAUSE

    -- Directional keys
    ArrowLeft = 174, -- INPUT_CELLPHONE_LEFT
    ArrowRight = 175, -- INPUT_CELLPHONE_RIGHT
    ArrowUp = 172, -- INPUT_CELLPHONE_UP
    ArrowDown = 173, -- INPUT_CELLPHONE_DOWN
    Enter = 176, -- INPUT_CELLPHONE_SELECT
    Backspace = 177, -- INPUT_CELLPHONE_CANCEL

    -- Function Keys
    F1 = 288 , -- INPUT_REPLAY_START_STOP_RECORDING
    F2 = 289 , -- INPUT_REPLAY_START_STOP_RECORDING_SECONDARY
    F3 = 170 , -- INPUT_SELECT_CHARACTER_MULTIPLAYER
    F5 = 166 , -- INPUT_SELECT_CHARACTER_MICHAEL
    F6 = 167 , -- INPUT_SELECT_CHARACTER_FRANKLIN
    F7 = 168 , -- INPUT_SELECT_CHARACTER_TREVOR
    F8 = 169 , -- INPUT_SELECT_CHARACTER_MULTIPLAYER (Alternate)
    F9 = 56  , -- INPUT_DROP_WEAPON
    F10 = 57 , -- INPUT_DROP_AMMO
    F11 = 344, -- INPUT_SWITCH_VISOR
    
    -- Numpad keys
    Numpad0 = 96, -- INPUT_NUMPAD0
    Numpad1 = 97, -- INPUT_NUMPAD1
    Numpad2 = 98, -- INPUT_NUMPAD2
    Numpad3 = 99, -- INPUT_NUMPAD3
    Numpad4 = 100, -- INPUT_NUMPAD4
    Numpad5 = 101, -- INPUT_NUMPAD5
    Numpad6 = 102, -- INPUT_NUMPAD6
    Numpad7 = 103, -- INPUT_NUMPAD7
    Numpad8 = 104, -- INPUT_NUMPAD8
    Numpad9 = 105, -- INPUT_NUMPAD9
    NumpadPlus = 107, -- INPUT_NUMPADPLUS
    NumpadMinus = 109, -- INPUT_NUMPADMINUS
    NumpadMultiply = 106, -- INPUT_NUMPADMULTIPLY
    NumpadDivide = 111, -- INPUT_NUMPADDIVIDE
}